version: "3.1"

services:
  db:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
     - MONGO_INITDB_DATABASE=base
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  app:
    container_name: fastapp
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app/:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  celery_worker:
    image: celery:5.2.7
    container_name: celery_worker
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    volumes:
      - ./app/:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    image: mher/flower
    container_name: flower
    build: .

    ports:
      - 5555:5555
    volumes:
      - ./app/:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
      - celery_worker